# To load:

## This should be the results folder in your contact graspnet folder
## "predictions_" at the end should not be modified

results_path: "/home/zhihao/contact_graspnet_hoi/results/predictions_"
