# To save

## The npy path specifies the folder to save the generated npy file of depth image
## It's recommanded to create a "depth_image_data" folder in your contact graspnet folder

npy_path: "/home/zhihao/contact_graspnet/depth_image_data/"

## To visualize the calculation, some image is generated and saved according to the following path

image_path: "/home/zhihao/ws_hoi/src/vision/doc/pics/test/"
